### ISSUE TITLE
Compilation errors on Xubuntu 14.04

### ISSUE THREAD

**Issue by Calinou** [Nocte-/hexahedra#46]
All dependencies are installed, with the PPA being used.

```
[  3%] Built target run
[ 26%] Built target hexacommon
[ 73%] Built target hexaserver
[ 73%] Built target hexahedra-server
[ 74%] Building CXX object hexa/client/CMakeFiles/hexaclient.dir/sfml.cpp.o
In file included from /home/calinou/_VCS/hexahedra/hexa/client/sfml.hpp:49:0,
                 from /home/calinou/_VCS/hexahedra/hexa/client/sfml.cpp:22:
/home/calinou/_VCS/hexahedra/hexa/client/renderer_i.hpp: In constructor 'hexa::renderer_i::renderer_i(hexa::scene&)':
/home/calinou/_VCS/hexahedra/hexa/client/renderer_i.hpp:59:43: error: invalid initialization of non-const reference of type 'hexa::scene&' from an rvalue of type '<brace-enclosed initializer list>'
         , chunk_offset_{world_chunk_center}
                                           ^
make[2]: *** [hexa/client/CMakeFiles/hexaclient.dir/sfml.cpp.o] Error 1
make[1]: *** [hexa/client/CMakeFiles/hexaclient.dir/all] Error 2
make: *** [all] Error 2
```

BTW, how do you compile and _use_ the libraries from the Git repositories, instead of having to rely on a PPA?

**Comment by Nocte-** [comment]
I've just pushed a whole bunch of fixes, it should work fine with gcc again.

The three other libraries can be built in the same vein: cmake, make, sudo make install. Hexahedra's CMake config should pick them up automatically if they're installed in /usr/local (the default prefix if you're building them from Github) or /usr (where the PPA puts them).

I'll update the [wiki page](https://github.com/Nocte-/hexahedra/wiki/Building-on-Linux) with a more detailed description.

**Comment by Calinou** [comment]
This now:

```
[  3%] Built target run
[  4%] Building CXX object hexa/CMakeFiles/hexacommon.dir/http_cache.cpp.o
[  5%] [  6%] [  7%] [  8%] [  9%] Building CXX object hexa/server/CMakeFiles/hexaserver.dir/hndl.cpp.o
[ 10%] Building CXX object hexa/server/CMakeFiles/hexaserver.dir/init_terrain_generators.cpp.o
Building CXX object hexa/server/CMakeFiles/hexaserver.dir/terrain/transmute.cpp.o
Building CXX object hexa/server/CMakeFiles/hexaserver.dir/area/area_generator.cpp.o
[ 11%] Building CXX object hexa/server/CMakeFiles/hexaserver.dir/terrain/height_estimator.cpp.o
Building CXX object hexa/server/CMakeFiles/hexaserver.dir/terrain/soil_generator.cpp.o
Building CXX object hexa/server/CMakeFiles/hexaserver.dir/terrain/object_placer.cpp.o
/home/calinou/_VCS/hexahedra/hexa/http_cache.cpp:28:43: fatal error: boost/network/protocol/http.hpp: No such file or directory
 #include <boost/network/protocol/http.hpp>
                                           ^
compilation terminated.
In file included from /home/calinou/_VCS/hexahedra/hexa/server/hndl.cpp:22:0:
/home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp:25:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/hndl.cpp:22:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
In file included from /home/calinou/_VCS/hexahedra/hexa/server/area/area_generator.cpp:27:0:
/home/calinou/_VCS/hexahedra/hexa/server/area/../hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/area/../hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/area/../hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/area/area_generator.hpp:25:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/area/area_generator.cpp:22:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
/home/calinou/_VCS/hexahedra/hexa/server/hndl.cpp: In function 'std::unique_ptr<hexa::noise::generator_i> hexa::compile_hndl(const string&, const string&)':
/home/calinou/_VCS/hexahedra/hexa/server/hndl.cpp:54:47: error: forming reference to void
     auto& n = gen_ctx->set_script(name, script);
                                               ^
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/area/area_generator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/calinou/_VCS/hexahedra/hexa/server/hndl.cpp:68:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/height_estimator.cpp:24:0:
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/height_estimator.hpp:25:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/terrain/height_estimator.cpp:22:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
In file included from /home/calinou/_VCS/hexahedra/hexa/server/init_terrain_generators.cpp:29:0:
/home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/hndl.hpp:25:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/init_terrain_generators.cpp:29:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/hndl.cpp.o] Error 1
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/transmute.cpp:29:0:
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/transmute.hpp:26:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/terrain/transmute.cpp:22:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/transmute.cpp:29:0:
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:64:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/terrain/transmute.cpp.o] Error 1
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/terrain/height_estimator.cpp.o] Error 1
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/object_placer.hpp:25:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/terrain/object_placer.cpp:22:
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:25:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/terrain/object_placer.hpp:25,
                 from /home/calinou/_VCS/hexahedra/hexa/server/terrain/object_placer.cpp:22:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/soil_generator.cpp:26:0:
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp: In function 'hexa::array_3d<double, 16ul, 16ul, 16ul> hexa::hndl_chunk(hexa::noise::generator_i&, hexa::chunk_coordinates)':
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: error: no matching function for call to 'hexa::noise::generator_i::run(glm::detail::tvec3<double, (glm::precision)0u>, glm::dvec3, glm::ivec3)'
                    glm::ivec3(chunk_size, chunk_size, chunk_size));
                                                                  ^
/home/calinou/_VCS/hexahedra/hexa/server/terrain/../hndl.hpp:63:66: note: candidate is:
In file included from /home/calinou/_VCS/hexahedra/hexa/server/terrain/soil_generator.hpp:26:0,
                 from /home/calinou/_VCS/hexahedra/hexa/server/terrain/soil_generator.cpp:22:
/usr/include/hexanoise/generator_i.hpp:38:33: note: virtual std::vector<double> hexa::noise::generator_i::run(const dvec2&, const dvec2&, const ivec2&)
     virtual std::vector<double> run(const glm::dvec2& corner,
                                 ^
/usr/include/hexanoise/generator_i.hpp:38:33: note:   no known conversion for argument 1 from 'glm::detail::tvec3<double, (glm::precision)0u>' to 'const dvec2& {aka const glm::detail::tvec2<double, (glm::precision)0u>&}'
make[2]: *** [hexa/CMakeFiles/hexacommon.dir/http_cache.cpp.o] Error 1
make[1]: *** [hexa/CMakeFiles/hexacommon.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/init_terrain_generators.cpp.o] Error 1
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/terrain/soil_generator.cpp.o] Error 1
make[2]: *** [hexa/server/CMakeFiles/hexaserver.dir/terrain/object_placer.cpp.o] Error 1
make[1]: *** [hexa/server/CMakeFiles/hexaserver.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by Nocte-** [comment]
Sorry about that! Could you apt-get libcurl4-openssl-dev and libhexanoise1-dev (0.2.1 now), and try again?

**Comment by Calinou** [comment]
Still happens after using `make clean` and `cmake .`, which reports no missing dependencies:

```
[  3%] Built target run
[  4%] Building CXX object hexa/CMakeFiles/hexacommon.dir/http_cache.cpp.o
[ 52%] Built target hexaserver
/home/calinou/_VCS/hexahedra/hexa/http_cache.cpp:28:43: fatal error: boost/network/protocol/http.hpp: No such file or directory
 #include <boost/network/protocol/http.hpp>
                                           ^
compilation terminated.
make[2]: *** [hexa/CMakeFiles/hexacommon.dir/http_cache.cpp.o] Error 1
make[1]: *** [hexa/CMakeFiles/hexacommon.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Nocte-** [comment]
Could you try a git pull? The hexa/http_cache.\* files should be gone.

**Comment by Calinou** [comment]
This works, thanks.
